version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm test
  push-and-pull-translations-on-master:
    docker:
      - image: circleci/java:latest
    steps:
      - checkout
      - run:
          name: Download CrowdIn CLI
          command: |
            wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
            sudo dpkg -i crowdin.deb
      - run:
          name: Push translations
          command: crowdin push -b master
      - run:
          name: Pull translations
          command: crowdin pull -b master
      - persist_to_workspace:
          root: .
          paths:
            - translations
  push-translations:
    docker:
      - image: circleci/java:latest
    steps:
      - checkout
      - run:
          name: Download CrowdIn CLI
          command: |
            wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
            sudo dpkg -i crowdin.deb
      - run:
          name: Push translations
          command: crowdin push -b ${CIRCLE_BRANCH}
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
      - run:
          name: Release to GitHub
          command: npm run release-to-github
      - run:
          name: Publish on npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish --access=public
  docs:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build docs
          command: npm run build-docs
      - run:
          name: Deploy docs
          command: |
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "CircleCI"
            npm run deploy-docs

workflows:
  version: 2
  build-test-release-and-build-docs:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - push-and-pull-translations-on-master:
          filters:
            branches:
              only: master
      - push-translations:
          filters:
            branches:
              ignore:
                - gh-pages
                - master
      - test:
          requires:
            - build
      - release:
          filters:
            branches:
              only: master
          requires:
            - test
            - push-and-pull-translations-on-master
      - docs:
          requires:
            - test
          filters:
            branches:
              only: master